### ISSUE TITLE
Android approach

### ISSUE THREAD

**Issue by stefanhuber** [nativescript-community/insomnia#7]
In Android there is the PowerManager class (https://developer.android.com/reference/android/os/PowerManager). The class allows for enabling and disabling the wakelock (requires permission). Wouldn't this be a better approach than the foreground service?

Was there any other intention or concern, not to use PowerManager?

Thx!

**Comment by EddyVerbruggen** [comment]
Never considered it, but if it requires a permission and adding a window flag doesn’t, then that’s a good eason not to use it.

Any specific concerns with the current approach?

**Comment by stefanhuber** [comment]
Yes it requires a permission. I was just wondering what is the right approach or if some devices or android versions might ignore one of the approaches. As I found a resource on Android docs https://developer.android.com/training/scheduling/wakelock it seems that FLAG_KEEP_SCREEN_ON is perfectly ok.

thx for your answer.

**Comment by EddyVerbruggen** [comment]
Cheers! FWIW I've never heard anyone complain about it not working on Android across this plugin and the Cordova version I'm also maintaining.

Have a good day!
